# Generated by Django 4.0.6 on 2022-08-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort', models.CharField(max_length=255)),
                ('poroda', models.CharField(max_length=255)),
                ('razmer', models.IntegerField(default=2500)),
            ],
            options={
                'verbose_name': 'Паркетная доска',
                'verbose_name_plural': 'Паркетные доски',
            },
        ),
    ]
