# Generated by Django 4.0.6 on 2022-09-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Select',
            new_name='Massiv',
        ),
        migrations.AlterModelOptions(
            name='massiv',
            options={'verbose_name': 'Паркет массив', 'verbose_name_plural': 'Паркет массив'},
        ),
    ]
