# Generated by Django 4.0.6 on 2022-09-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_select_massiv_alter_massiv_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massiv',
            name='razmer',
        ),
        migrations.AddField(
            model_name='massiv',
            name='opis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='massiv',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='massiv',
            name='poroda',
            field=models.CharField(max_length=255, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='massiv',
            name='sort',
            field=models.CharField(max_length=255, verbose_name='Сорт'),
        ),
    ]
