# Generated by Django 4.0.6 on 2022-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_massiv_razmer_massiv_opis_alter_massiv_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shpon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('poroda', models.CharField(max_length=255, verbose_name='Порода')),
                ('thickness', models.CharField(max_length=255, verbose_name='Название')),
                ('opis', models.TextField()),
            ],
            options={
                'verbose_name': 'Шпон',
                'verbose_name_plural': 'Шпон',
            },
        ),
    ]
