# Generated by Django 4.0.6 on 2022-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shpon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shpon',
            name='thickness',
            field=models.IntegerField(verbose_name='Толщина'),
        ),
    ]
